sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t evilbook/docker-react .





script:
  - docker run -e CI=true evilbook/docker-react npm run test